version: "2.1"

networks:
  ps:

services:

  clean:
    image: clean
    container_name: ps-cleansrv
    ports:
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8082:8082"
    depends_on:
      "postgresql":
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 8001"]
    networks:
      - ps


  postgresql:
    image: postgres:14-alpine
    container_name: ps-sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps
    healthcheck:
      test: pg_isready -U postgres

  mongo:
    image: mongo:latest
    container_name: ps-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ps

  prometheus:
    image: prom/prometheus:latest
    volumes: 
      - ./prometheus:/prometheus/
    command:
      - --config.file=/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - "3000:3000"
    volumes: 
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    networks:
      - ps

volumes:
  mongo_data:
  grafana-data: